### ISSUE TITLE
cant run it

### ISSUE THREAD

**Issue by TheCodeInjection** [lightaime/camel#101]
python examples/ai_society/role_playing.py
Traceback (most recent call last):
  File "examples/ai_society/role_playing.py", line 3, in <module>
    from camel.agents import RolePlaying
ModuleNotFoundError: No module named 'camel'

**Comment by lightaime** [comment]
Hi @TheCodeInjection, did you do `pip install -e .` for the package?

**Comment by TheCodeInjection** [comment]
yes

**Comment by lightaime** [comment]
I closed this issue. Please feel free to reopen if it is not fixed.
