### ISSUE TITLE
What is the function of the <YOUR_SOLUTION> block?

### ISSUE THREAD

**Issue by lowpair** [lightaime/camel#102]
The prompt in the project contains<YOU_ SOLUTION>information, but no alternative logic was found in the code.

**Comment by lowpair** [comment]
So what is the specific purpose of <YOU_ SOLUTION>?

According to normal logic, it should have been replaced as an<LANGUAGE>, but if it is not replaced, then it will be input by the openAI API and output as it was originally?

**Comment by lightaime** [comment]
It is a placeholder for the output solution from LLMs and hopefully LLMs will replace it.

**Comment by lightaime** [comment]
I closed it. Let me if the issue remains.
