### ISSUE TITLE
Issue modifying default assistant/user prompts

### ISSUE THREAD

**Issue by markf278** [lightaime/camel#104]
Hey I'm trying to edit the default assistant/user prompts in camel\agents\prompts\ai_society but I'm getting the error in the attached image:

  File "C:\tools\camel\camel\generators.py", line 46, in validate_meta_dict_keys
    raise ValueError("The keys of the meta_dict should be in "
ValueError: The keys of the meta_dict should be in set(). Got {'<USER_ROLE>', '<TASK>', '<ASSISTANT_ROLE>'} instead.

Here are the custom Assistant/User prompt I want to include:
Proteus 4.2 - OmniCompetent Assistant: https://flowgpt.com/prompt/Ku_FbNzQsd_itThT7xhY6
Tech writer/Super AI researcher - Dr. Ada Turing: https://flowgpt.com/prompt/3EB4JHHhJPiP51f9fA9Bf

The PersRubric/Omnicomps in the above are quite interesting and...effective, I want to use Camel to test how effective they actually are by doing a few hundred runs with variations of the above vs default settings. 

![image](https://user-images.githubusercontent.com/126211318/236098704-f9f46a89-75eb-458a-b583-00273c1f42ca.png)

**Comment by markf278** [comment]
This isnt an issue... so you can close it, just not sure where else to ask.

**Comment by lightaime** [comment]
Sorry for the late reply. It seems to be a problem that the `meta_dict` does not match with the `keywords` in the prompt. Did you manage to fix it?
