### ISSUE TITLE
Could you please fix <br> tag for code in the sample gradio demo?

### ISSUE THREAD

**Issue by yhyu13** [lightaime/camel#48]
Just had a try at http://agents.camel-ai.org/

![2023-04-04_00-51](https://user-images.githubusercontent.com/19365678/229576165-08a27f66-308d-4a56-a8f7-b53f8cd67ee2.png)

But what the model spits out contains ```<br>``` html tag which makes them a lot harder to use

Thank! Your work is amazing, it opens up a lot of possibilities, especially in eduacting onself in learning something new w/o knowing much but just a couples ideas.
This work deserve more attention!

**Comment by lightaime** [comment]
Thanks for your kind words! Thanks for pointing this out. We also realized this problem. It is a rendering issue in gradio. @Obs01ete is working on fixing it. Thanks!

**Comment by Obs01ete** [comment]
On it

**Comment by Obs01ete** [comment]
@yhyu13 Please check the fixed code blocks in the app:
http://agents.camel-ai.org/
