### ISSUE TITLE
Gradio for Local Use Case? - Enhancement

### ISSUE THREAD

**Issue by Meathelix1** [lightaime/camel#53]
Hello, I noticed that you have Gradio for the demo however can we also get this for local use?

**Comment by Obs01ete** [comment]
Hi @Meathelix1 thanks for your interest. Here is the source code of the Data Explorer and Agents apps:
https://github.com/lightaime/camel/tree/master/apps
Which one are you interested in?

**Comment by Obs01ete** [comment]
I consider the issue resolved
