### ISSUE TITLE
Code examples appear broken? 

### ISSUE THREAD

**Issue by Atlas3DSS** [lightaime/camel#65]
Followed instructions to try and test the roleplaying example but it just errors out. would appreciate some guidance. Do we need to change or move the examples out of the folder - the instructions appear to suggest you just run the example demo from its location. GPT 4 suggestions were a bust. 

PS D:\camel\camel\agent> python .\role_playing.py
Traceback (most recent call last):
  File "D:\camel\camel\agent\role_playing.py", line 7, in <module>
    from .chat_agent import ChatAgent
ImportError: attempted relative import with no known parent package
PS D:\camel\camel\agent>

**Comment by lightaime** [comment]
Could you please check if 
`pip list | grep camel` 
 to see if the package is installed correctly?

**Comment by lightaime** [comment]
You may be running a wrong file. 
The demo file is under `examples`
`python examples/ai_society/role_playing.py`

**Comment by Atlas3DSS** [comment]
> You may be running a wrong file. The demo file is under `examples` `python examples/ai_society/role_playing.py`

thats what i thought too so i went to try and run that one and got a different kind of error. 

![image](https://user-images.githubusercontent.com/89653506/230704442-9352afbc-835a-444e-b309-db89ab6d84d6.png)
camel does appear installed 

![image](https://user-images.githubusercontent.com/89653506/230704447-f92b04b1-5e31-405d-a04d-567ddb2df236.png)
when i tried to run the other version - but thats weird cause the txt file is definitely there.

**Comment by lightaime** [comment]
I see. It seems like a backslash in Windows. I only test it on OS and Linux. I think using `pathlib` for paths may fix this issue.

**Comment by lightaime** [comment]
I will need to fix it a late later today. Sorry that I am away from my computer.

**Comment by Atlas3DSS** [comment]
> I will be only able to fix it a late later today. Sorry that I am away from my computer.

i appreciate your help :D thank you for even looking into this now. 
![image](https://user-images.githubusercontent.com/89653506/230705325-14a88a12-6e3e-4dd8-b539-0bfd5310d052.png)
i did try and load it on my WSL instance as well  - no dice there same error. 

Thank you again - hope you have a nice evening - ill keep derping around.

**Comment by lightaime** [comment]
It seems to be a path problem. Could you run it from the project root directory?

`python examples/ai_society/role_playing.py`

**Comment by lightaime** [comment]
You can also try the colab if it doesn’t work. I will look into it later and let you know.

**Comment by Atlas3DSS** [comment]
> It seems to be a path problem. Could you run it from the project root directory?
> 
> `python examples/ai_society/role_playing.py`

This was it rigfht here - i just needed to run it from root - i am sorry for being a newb - thank you very much for your help.

**Comment by lightaime** [comment]
No worries. Enjoy!
