### ISSUE TITLE
Add `pytest` to Github workflow

### ISSUE THREAD

**Issue by lightaime** [lightaime/camel#86]

**Comment by kanukolluGVT** [comment]
Hello Dmitrii Khizbullin,

I hope this message finds you well. My name is Goutham, and I am writing to you from India. I am currently working as a Machine Learning Engineer with over a year of experience. I have been exploring the world of open source and came across your repository. I was impressed by the work you have done, and I would like to contribute to it.

I am eager to start contributing to your repository, and I can allocate one hour per day to this work. This is my first time contributing to an open-source project, and I am excited to begin with your repository.

Thank you for taking the time to read my message. I look forward to hearing from you soon.

Best regards,

Goutham

**Comment by lightaime** [comment]
Welcome to CAMEL @kanukolluGVT. Glad that you would like to contribute. Looking forward to it!
